# Generated by Django 4.1.7 on 2023-04-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myauth', '0002_userprofile_name_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['role'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='role', to='auth.group', verbose_name='Роль'),
        ),
    ]
