# Generated by Django 4.1.7 on 2023-04-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myauth', '0004_userprofile_role_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, related_name='role', to='auth.group', verbose_name='Роль'),
        ),
    ]
