# Generated by Django 4.1.7 on 2023-04-09 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not paid', 'Не оплачен'), ('Paid', 'Оплачен'), ('Delivery', 'Доставляется'), ('Awaiting', 'Ожидает выдачи'), ('Done', 'Выдан')], default='Not paid', max_length=15, verbose_name='Статус доставки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
