# Generated by Django 4.1.7 on 2023-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='test@test.ru', max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=7000000000, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.CharField(default='test', max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
