# Generated by Django 4.1.7 on 2023-04-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myorder', '0002_alter_order_status_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Card', 'Онлайн картой'), ('Other', 'Онлайн со случайного чужого счета')], default='Card', max_length=10)),
                ('summary_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myorder.order')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
