# Generated by Django 4.1.7 on 2023-04-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0003_alter_order_user'),
        ('mypayment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myorder.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Онлайн картой'), ('Other', 'Онлайн со случайного чужого счета')], default='Card', max_length=10, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='summary_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Общая стоимость'),
        ),
    ]
