# Generated by Django 4.1.7 on 2023-04-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0002_producttags_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='mycatalog.producttags', verbose_name='Тэг'),
        ),
    ]
