# Generated by Django 4.1.7 on 2023-04-09 16:29

from django.db import migrations, models
import django.db.models.deletion
import mycatalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0003_remove_product_tags_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='mycatalog.producttags', verbose_name='Тэг'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=mycatalog.models.product_directory_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycatalog.product', verbose_name='Продукт')),
            ],
        ),
    ]
