# Generated by Django 4.1.7 on 2023-04-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0004_alter_product_tags_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='mycatalog.product', verbose_name='Продукт'),
        ),
    ]
