# Generated by Django 4.1.7 on 2023-04-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
