# Generated by Django 4.1.7 on 2023-04-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='Ограниченный тираж'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='chosen',
            field=models.BooleanField(default=False, verbose_name='Избранный'),
        ),
    ]
